### ISSUE TITLE
[PE-D][Tester D] Bug Report: Texts overspill causing text to not be able to be seen

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103-W16-2/tp#174]
![image.png](https://raw.githubusercontent.com/jundatan/ped/main/files/d2e3c0d0-714a-4c0b-868d-dc6dc55fde98.png)

Texts overspill when trying to add/edit a component with a very long String as shown above.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: jundatan/ped#2

**Comment by dsja612** [comment]
Fixed locally, will push soon

**Comment by dsja612** [comment]
Need to add to DG

**Comment by UnwilledTangent** [comment]
Closed. Duplicate with Issue #200 .
