### ISSUE TITLE
[PE-D][Tester D] Bug Report: UG command summary

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103-W16-2/tp#176]
![image.png](https://raw.githubusercontent.com/jundatan/ped/main/files/e1b00cac-07f3-46d3-8a2f-fab0b1a373a1.png)

Command Summary for the UG does not reflect all the commands like name.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: jundatan/ped#4

**Comment by amoonguss1** [comment]
Hi, thanks for highlighting this, I've updated the UG's command summary.
