### ISSUE TITLE
[PE-D][Tester D] Bug Report: Salary should be more than 0

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103-W16-2/tp#180]
![image.png](https://raw.githubusercontent.com/jundatan/ped/main/files/bf41507f-4471-46be-8fb3-ad7fd7f1260d.png)

Able to edit the role with a salary of 0.

![image.png](https://raw.githubusercontent.com/jundatan/ped/main/files/3bee1cb4-3f07-4c84-b134-8b577ebbade4.png)

But error message says that Salaries should be more than 0 when trying to edit with a String instead of a Number.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: jundatan/ped#6

**Comment by pzaiming** [comment]
Thanks for the bug finding. Updated the error message clearer and also checks that only positive number (> 0) up to 2dp will be accepted.

**Comment by pzaiming** [comment]
Thanks for the bug finding. Updated the error message clearer and also checks that only positive number (> 0) up to 2dp will be accepted.
