### ISSUE TITLE
[PE-D][Tester D] Bug report: Deadline edit

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103-W16-2/tp#184]
![image.png](https://raw.githubusercontent.com/jundatan/ped/main/files/8bb2ce5d-d267-442b-919a-36220c3e2b39.png)

Tried entering to edit Role 1 with a new deadline (Date that does not exist) but found that editing the deadline does not work with no error messages too.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: jundatan/ped#8

**Comment by RyanQiu1** [comment]
Fixed as of current update

**Comment by RyanQiu1** [comment]
Close as approved as bug, does not function as UG stated.
