### ISSUE TITLE
[PE-D][Tester D] Bug Report: UG picture example

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103-W16-2/tp#197]
![image.png](https://raw.githubusercontent.com/jundatan/ped/main/files/28de01f8-7579-480e-97b5-62323b9101dd.png)

Picture does not match the example. Potential UG bug.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: jundatan/ped#12

**Comment by RyanQiu1** [comment]
Fixed as of next update.
