### ISSUE TITLE
[PE-D][Tester D] Bug Report: UG General Commands

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103-W16-2/tp#201]
![image.png](https://raw.githubusercontent.com/jundatan/ped/main/files/a761e945-c2b8-451b-97e7-b66c7ab5a410.png)

Help command does not display user guide. 

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: jundatan/ped#14

**Comment by RyanQiu1** [comment]
Fixed in next update.
