### ISSUE TITLE
[PE-D][Tester B] Deadline parameter does not follow specified restriction (not over current date)

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103-W16-2/tp#204]
According to the User Guide, the specified restriction for deadlines is that it should **not be over** the current date. However, deadlines which are not over the current date are not accepted.

After further testing, it appears that the intended restriction is that only deadlines **over** the current date are accepted. Hence, the User Guide should reflect this to be consistent with the product.

![ug.png](https://raw.githubusercontent.com/LeonardYam/ped/main/files/e4b5daad-c54b-47cf-b22a-bbb4b94dd552.png)

![image.png](https://raw.githubusercontent.com/LeonardYam/ped/main/files/13e2833a-b032-4ecf-967b-ca2dfde4cba9.png)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: LeonardYam/ped#3

**Comment by RyanQiu1** [comment]
Duplicate issue fixed.
