### ISSUE TITLE
[PE-D][Tester A] Current date not accepted by deadline parameter

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103-W16-2/tp#212]
![Screen Shot 2023-03-31 at 4.10.54 PM.png](https://raw.githubusercontent.com/ChangGittyHub/ped/main/files/bd2b4146-0ef7-4a2e-bf4e-51bdd5735c39.png)
I realized that current date is not accepted which does not match the restriction as described.
Maybe it would be clearer if it was stated that current date and later is not accepted.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: ChangGittyHub/ped#12

**Comment by RyanQiu1** [comment]
Fixed as of current update.
