### ISSUE TITLE
[PE-D][Tester B] Salary values are not parsed correctly

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103-W16-2/tp#213]
Salary parameter does not parse zero-padded numbers correctly, and stores it with the zero-padded values.

Would it be better if the parser removes zero-padding from inputs?

![image.png](https://raw.githubusercontent.com/LeonardYam/ped/main/files/e73c66c3-3698-432b-b501-186e0fb8d6b8.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: LeonardYam/ped#6

**Comment by pzaiming** [comment]
Thanks for highlighting this issue! 
Issue have been fixed to disallow the left padding of zeroes to salary.
