### ISSUE TITLE
[code] Change command parameter for salary

### ISSUE THREAD

**Issue by amoonguss1** [AY2223S2-CS2103-W16-2/tp#242]
Unnecessarily complicated (or hard-to-type) command formats can be considered a type.FeatureFlaw as it is expected that the input formats will be optimized to get things done fast. Some examples:  using hard-to-type special characters such as $/ in the format when it is possible to avoid them.

**Comment by dsja612** [comment]
Not a big deal since you could easily press `shift` + `4` as a fast typist, but let's see what others think

**Comment by pzaiming** [comment]
I think its better to standardize as the  `s/` is not currently used and might be better and more intuitive too.

**Comment by UnwilledTangent** [comment]
I agree, closing issue as a feature flaw. Added to DG.
